site_name: Spatial Data of Municipalities (Maps)
theme_dir: cinder
copyright: "Spatial Data of Municipalities (Maps)  is licensed under the <a href='Creative Commons Attribution-ShareAlike 2.5 India'>Creative Commons Attribution-ShareAlike 2.5 India</a>"
pages:
    - Home: index.md
    - Contributing: contributing.md
    - Reference: reference.md
    - Municipalities:
        - Ahmedabad: ahmedabad.md
        - Bangalore: bangalore.md
        - Pune: pune.md
    - Maps:
      - 'Assembly Constituencies': 'assembly-constituencies.md'
      - 'Parliamentary constituencies': 'parliamentary-constituencies.md'
      - 'States': 'states.md'
      - 'Districts': 'districts.md'
      - 'Spatial data of Municipalities': 'index.md'
      - 'India Village Boundaries(Maps)': 'indian_village_boundaries.md'
site_dir: './../docs'
extra_css:
    - css/extra.css
